# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon Apr 11 19:43:51 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MainTextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.MainTextBox.setObjectName("MainTextBox")
        self.gridLayout.addWidget(self.MainTextBox, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NewButtonButton = QtWidgets.QPushButton(self.centralwidget)
        self.NewButtonButton.setObjectName("NewButtonButton")
        self.horizontalLayout.addWidget(self.NewButtonButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.BottomDock = QtWidgets.QDockWidget(MainWindow)
        self.BottomDock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BottomDock.setAutoFillBackground(False)
        self.BottomDock.setStyleSheet("Margin: 0px;")
        self.BottomDock.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.BottomDock.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.BottomDock.setObjectName("BottomDock")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MainCommandBox = QtWidgets.QPlainTextEdit(self.dockWidgetContents_2)
        self.MainCommandBox.setReadOnly(True)
        self.MainCommandBox.setObjectName("MainCommandBox")
        self.horizontalLayout_3.addWidget(self.MainCommandBox)
        self.BottomDock.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.BottomDock)
        self.RightDock = QtWidgets.QDockWidget(MainWindow)
        self.RightDock.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.RightDock.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.RightDock.setObjectName("RightDock")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RightDock.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.RightDock)
        self.LeftDock = QtWidgets.QDockWidget(MainWindow)
        self.LeftDock.setEnabled(True)
        self.LeftDock.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.LeftDock.setObjectName("LeftDock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LeftDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.LeftDock)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionButton = QtWidgets.QAction(MainWindow)
        self.actionButton.setObjectName("actionButton")
        self.actionCommand_Window = QtWidgets.QAction(MainWindow)
        self.actionCommand_Window.setObjectName("actionCommand_Window")
        self.actionShortcuts = QtWidgets.QAction(MainWindow)
        self.actionShortcuts.setObjectName("actionShortcuts")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionOpen)
        self.menuNew.addAction(self.actionButton)
        self.menuNew.addAction(self.actionCommand_Window)
        self.menuEdit.addAction(self.actionShortcuts)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuNew.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NewButtonButton.setText(_translate("MainWindow", "NewButton"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As ..."))
        self.actionButton.setText(_translate("MainWindow", "Button"))
        self.actionCommand_Window.setText(_translate("MainWindow", "Command Window"))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

